import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Link  from 'next/link';


const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: "NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{
          background: "#EF9A9A",
          color: "-moz-initial",
          fontFamily: "cursive",
          fontSize:"20px",
          display:"flex",
          justifyContent: "right",
          alignItems:"right",
          gap:"40px",
          paddingRight:"40px"
        }}>
          <Link style={{margin: "10px"}}href="/">Home</Link>
          <Link style={{margin: "10px"}}href="posts">Posts</Link>
          <Link style={{margin: "10px"}}href="articles">Article</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
