export const metadata = {
    title: "Articles",
    description: "Generated by new logo",
};


export default function({children}){
    

    return(
        <div>
            <h1> Articles </h1>
            <div style={{
                marginTop:"50px",
                background:"blue",
                padding:"30px",
                borderRadius:"11px"
            }}
            >
                {children}</div>
        </div>

    )
}