
//export const metadata = {
//    title: "Articles",
//    description: "Generated by new logo",
//};
export default function ArticlesPage(){

    return(
        <div>
            <h1>Articles Page</h1>
            <p>The page Articles Page!</p>
        </div>
    )
}