
//export const metadata = {
//    title: "Articles",
//    description: "Generated by new logo",

import Todo from "../components/todo";

//};
export default async function ArticlesPage(){
    const response = await fetch('https://jsonplaceholder.typicode.com/todos/1')
    const todos = await response.json();

    return(
        <div>
            <h1>Articles Page</h1>
            <p>The page Articles Page!</p>

            <div>
                <Todo />
            </div>
        </div>
        
    )
}